const express=require('express');
const router=express.Router();
const adminController=require('../controllers/adminController');
const profileController=require('../controllers/profileController');
const authenticateAdmin=require('../middlewaress/checkAdmin');
router.post('/signIn',adminController.signInUser);
router.get('/users',authenticateAdmin,adminController.getAllUsers);
router.get('/users/:id',authenticateAdmin,profileController.getProfileForAdmin);
router.patch('/users/:id/status',authenticateAdmin,adminController.updateUserStatus);
router.delete('/users/:id',authenticateAdmin,adminController.deleteUserAndProfile);
router.get('/jobs',authenticateAdmin,adminController.getAllJobs);
router.get('/jobs/:id',authenticateAdmin,adminController.getOneJob);
router.patch('/jobs/:id/status',authenticateAdmin,adminController.toggleJobApproval);
router.delete('/jobs/:id',authenticateAdmin,adminController.deleteJob);
router.get('/orders',authenticateAdmin,adminController.getPremiumPurchases);
router.get('/stats',authenticateAdmin,adminController.getAdminStats);
router.get('/applications',authenticateAdmin,adminController.getAllApplications);
module.exports=router;